/** @type {import('tailwindcss').Config} */
// GENERATED by scripts/tailwind-precompile.py - rerun that rather than hand-editing.
// Build: <tailwindcss> -c tailwind.config.js -i src/input.css -o styles.css --minify
// Replaces the runtime cdn.tailwindcss.com JIT compiler with a precompiled stylesheet.
// Any class added to this site LATER needs a rebuild or it will not exist in the CSS.
module.exports = {
    theme: {
      extend: {
        colors: {
          pomegranate: {
            DEFAULT: "#fb4d1c",
            light: "#fc8260",
            dark: "#c83d16",
            darker: "#641e0b",
            lightest: "#feede8",
            lighter: "#fedbd1",
          },
          jaffa: {
            DEFAULT: "#f28c34",
            dark: "#c17029",
            light: "#f5ae70",
            lightest: "#fdf3ea",
            lighter: "#fce8d6",
          },
          ink: {
            DEFAULT: "#191919",
            soft: "#4c4c4c",
            muted: "#7f7f7f",
            line: "#e5e5e5",
            bg: "#f2f2f2",
          },
        },
        fontFamily: {
          display: ["\"Yanone Kaffeesatz\"", "Impact", "sans-serif"],
          body: ["\"Hind\"", "system-ui", "sans-serif"],
        },
      },
    },
    content: ["./*.html", "./regrouting-geelong/*.html", "./regrouting-warrnambool/*.html", "./regrouting-werribee/*.html", "./service-areas/*.html", "./services/*.html", "./regrouting-geelong/*.js", "./regrouting-warrnambool/*.js", "./regrouting-werribee/*.js"],
  }
